//Login
const LOGIN = 'LOGIN'

//Register
const REGISTER = 'REGISTER'

//Get Categories
const GET_CATEGORIES = 'GET_CATEGORIES'

//Get Produit
const GET_PRODUIT = 'GET_PRODUIT'
//Get Produit by id
const GET_PRODUIT_BY_CATEGORIESID = 'GET_PRODUIT_BY_CATEGORIESID'
// Get history article
const GET_HISTORY_ARTICLE = 'GET_HISTORY_ARTICLE'
const GET_PRODUCT_BY_INPUT_TEXT = 'GET_PRODUCT_BY_INPUT'

//Get article by id
const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID'

const GET_UNIT_TYPE = 'GET_UNIT_TYPE';
const GET_PROFILE = "GET_PROFILE";

// Get history article vendeur
export const GET_HISTORY_ARTICLE_VENDEUR = 'GET_HISTORY_ARTICLE_VENDEUR'

//GET Location
const GET_LOCATION_GOOGLE_MAP = 'GET_LOCATION_GOOGLE_MAP'

const GET_LOCATION_GOOGLE_MAP_REDUCER = 'GET_LOCATION_GOOGLE_MAP_REDUCER'

const CREATE_ARTICLE_BY_USER = 'CREATE_ARTICLE_BY_USER'

const SEND_DEVICE_TOKEN_CUSTOMER = 'SEND_DEVICE_TOKEN_CUSTOMER'

const FORGOT_PASSWORD = 'FORGOT_PASSWORD'

const SEND_DT_PROVIDER = "SEND_DT_PROVIDER"

const DELETE_END_POINT = "DELETE_END_POINT"

const UPDATE_PROFILE = "UPDATE_PROFILE"

const IS_UPDATE_PROFILE = "IS_UPDATE_PROFILE"

const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"

const CHANGE_PASSWORD = "CHANGE_PASSWORD"

const IS_CREATE_ARTICLE = "IS_CREATE_ARTICLE"

const QUICKLY_CREATE_ARTICLE = "QUICKLY_CREATE_ARTICLE"

const CREATE_ARTICLE = "CREATE_ARTICLE"

const ADD_EVALUATION = "ADD_EVALUATION"

const UPDATE_ARTICLE = "UPDATE_ARTICLE"

const GET_AVATAR = "GET_AVATAR"

const UPDATE_AVATAR = "UPDATE_AVATAR"

const DEVICE_TOKEN = "DEVICE_TOKEN"

const RUN_FIRST_TIME = "RUN_FIRST_TIME"

const IS_FIRST_TIME = "IS_FIRST_TIME"

const REMEMBER_PRODUCT = "REMEMBER_PRODUCT"

const DELETE_ARTICLE = "DELETE_ARTICLE"

const GET_CERTIFICATE = "GET_CERTIFICATE"

const GET_CONDITION = "GET_CONDITION"

export {
    LOGIN,
    REGISTER,
    GET_UNIT_TYPE,
    GET_CATEGORIES,
    GET_PRODUIT,
    GET_PROFILE,
    GET_PRODUIT_BY_CATEGORIESID,
    GET_HISTORY_ARTICLE,
    GET_PRODUCT_BY_INPUT_TEXT,
    GET_ARTICLE_BY_ID,
    GET_LOCATION_GOOGLE_MAP,
    CREATE_ARTICLE_BY_USER,
    GET_LOCATION_GOOGLE_MAP_REDUCER,
    SEND_DEVICE_TOKEN_CUSTOMER,
    FORGOT_PASSWORD,
    SEND_DT_PROVIDER,
    DELETE_END_POINT,
    UPDATE_PROFILE,
    IS_UPDATE_PROFILE,
    UPDATE_PROFILE_SUCCESS,
    CHANGE_PASSWORD,
    IS_CREATE_ARTICLE,
    QUICKLY_CREATE_ARTICLE,
    CREATE_ARTICLE,
	ADD_EVALUATION,
	UPDATE_ARTICLE,
    GET_AVATAR,
    UPDATE_AVATAR,
    DEVICE_TOKEN,
    RUN_FIRST_TIME,
    IS_FIRST_TIME,
    REMEMBER_PRODUCT,
    DELETE_ARTICLE,
    GET_CERTIFICATE,
    GET_CONDITION
}
